// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type CreateUserDto = {
    password: string;
    email: string;
    role: 'candidate' | 'recruiter';
};

export type ObjectId = {
    [key: string]: unknown;
};

export type UserDto = {
    email: string;
    role: 'candidate' | 'recruiter' | 'admin';
    active: boolean;
    _id: ObjectId;
    createdAt: string;
    updatedAt: string;
};

export type PaginatedUserDto = {
    total: number;
    limit: number;
    offset: number;
    results: Array<UserDto>;
};

export type UpdateUserDto = {
    level?: 'intern' | 'junior' | 'middle' | 'senior';
    fullName?: string;
    phone?: string;
    email?: string;
    password?: string;
    role?: 'candidate' | 'recruiter';
};

export type LoginDto = {
    password: string;
    email: string;
};

export type LoginReponseDto = {
    access_token: string;
};

export type CreateCandidateDto = {
    email: string;
    fullName: string;
    skills: Array<string>;
    status: 'active' | 'inactive';
};

export type UpdateCandidateDto = {
    email?: string;
    fullName?: string;
    skills?: Array<string>;
    status?: 'active' | 'inactive';
};

export type CreateJobDto = {
    [key: string]: unknown;
};

export type JobsDto = {
    _id: string;
    title: string;
    company: string;
    location: string;
    status: 'open' | 'close';
    salaryMin?: number;
    salaryMax?: number;
    description?: string;
    createdAt: string;
    updatedAt: string;
    isApplied?: boolean;
    createdBy?: string;
};

export type UpdateJobDto = {
    [key: string]: unknown;
};

export type CreateJobCandidateDto = {
    job: string;
    status: 'applied' | 'interview' | 'approved' | 'rejected' | 'hired';
};

export type UpdateJobCandidateDto = {
    job?: string;
    status?: 'applied' | 'interview' | 'approved' | 'rejected' | 'hired';
};

export type CreateNotificationDto = {
    type: 'job_application' | 'application_approved' | 'application_rejected' | 'application_interview';
    title: string;
    message: string;
    recipient: string;
    sender?: string;
    job?: string;
    jobCandidate?: string;
    status?: 'unread' | 'read';
    metadata?: {
        [key: string]: unknown;
    };
};

export type SenderDto = {
    _id: string;
    email: string;
    fullName?: string;
};

export type JobDto = {
    _id: string;
    title: string;
    company: string;
};

export type JobCandidateDto = {
    _id: string;
    status: string;
};

export type NotificationDto = {
    _id: string;
    type: 'job_application' | 'application_approved' | 'application_rejected' | 'application_interview';
    status: 'unread' | 'read';
    title: string;
    message: string;
    recipient: string;
    sender?: SenderDto;
    job?: JobDto;
    jobCandidate?: JobCandidateDto;
    metadata?: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
};

export type UpdateNotificationDto = {
    status?: 'unread' | 'read';
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type AppControllerGetHelloResponses = {
    default: string;
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type UsersControllerCreateBulkData = {
    body: Array<CreateUserDto>;
    path?: never;
    query?: never;
    url: '/users/bulk';
};

export type UsersControllerCreateBulkErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: Array<CreateUserDto>;
};

export type UsersControllerCreateBulkError = UsersControllerCreateBulkErrors[keyof UsersControllerCreateBulkErrors];

export type UsersControllerCreateBulkResponses = {
    /**
     * All records has been successfully created.
     */
    201: Array<CreateUserDto>;
};

export type UsersControllerCreateBulkResponse = UsersControllerCreateBulkResponses[keyof UsersControllerCreateBulkResponses];

export type UsersControllerSearchAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/search';
};

export type UsersControllerSearchAllErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: unknown;
};

export type UsersControllerSearchAllResponses = {
    200: PaginatedUserDto;
};

export type UsersControllerSearchAllResponse = UsersControllerSearchAllResponses[keyof UsersControllerSearchAllResponses];

export type UsersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerRemoveErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerRemoveResponses = {
    default: string;
};

export type UsersControllerRemoveResponse = UsersControllerRemoveResponses[keyof UsersControllerRemoveResponses];

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerFindOneErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerFindOneResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type UsersControllerFindOneResponse = UsersControllerFindOneResponses[keyof UsersControllerFindOneResponses];

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerUpdateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerUpdateResponses = {
    default: string;
};

export type UsersControllerUpdateResponse = UsersControllerUpdateResponses[keyof UsersControllerUpdateResponses];

export type UsersControllerGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerGetAllUsersErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerGetAllUsersResponses = {
    default: Array<UserDto>;
};

export type UsersControllerGetAllUsersResponse = UsersControllerGetAllUsersResponses[keyof UsersControllerGetAllUsersResponses];

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerGetProfileErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerGetProfileResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type UsersControllerUpdateProfileData = {
    body: UpdateUserDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerUpdateProfileErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type UsersControllerUpdateProfileResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type UsersControllerUpdateProfileResponse = UsersControllerUpdateProfileResponses[keyof UsersControllerUpdateProfileResponses];

export type AuthControllerSignInData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type AuthControllerSignInErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type AuthControllerSignInResponses = {
    default: LoginReponseDto;
};

export type AuthControllerSignInResponse = AuthControllerSignInResponses[keyof AuthControllerSignInResponses];

export type AuthControllerRegisterData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/users/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
    default: string;
};

export type AuthControllerRegisterError = AuthControllerRegisterErrors[keyof AuthControllerRegisterErrors];

export type AuthControllerRegisterResponses = {
    /**
     * The record has been successfully created.
     */
    201: unknown;
};

export type CandidatesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/candidates';
};

export type CandidatesControllerFindAllErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CandidatesControllerFindAllResponses = {
    default: string;
};

export type CandidatesControllerFindAllResponse = CandidatesControllerFindAllResponses[keyof CandidatesControllerFindAllResponses];

export type CandidatesControllerCreateData = {
    body: CreateCandidateDto;
    path?: never;
    query?: never;
    url: '/candidates';
};

export type CandidatesControllerCreateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CandidatesControllerCreateResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CandidatesControllerCreateResponse = CandidatesControllerCreateResponses[keyof CandidatesControllerCreateResponses];

export type CandidatesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/candidates/{id}';
};

export type CandidatesControllerRemoveErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CandidatesControllerRemoveResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CandidatesControllerRemoveResponse = CandidatesControllerRemoveResponses[keyof CandidatesControllerRemoveResponses];

export type CandidatesControllerUpdateData = {
    body: UpdateCandidateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/candidates/{id}';
};

export type CandidatesControllerUpdateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CandidatesControllerUpdateResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CandidatesControllerUpdateResponse = CandidatesControllerUpdateResponses[keyof CandidatesControllerUpdateResponses];

export type CandidatesControllerGetCandidateByEmailData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/candidates/email';
};

export type CandidatesControllerGetCandidateByEmailErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CandidatesControllerGetCandidateByEmailResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CandidatesControllerGetCandidateByEmailResponse = CandidatesControllerGetCandidateByEmailResponses[keyof CandidatesControllerGetCandidateByEmailResponses];

export type JobsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        location?: string;
        minSalary?: number;
        maxSalary?: number;
    };
    url: '/jobs';
};

export type JobsControllerFindAllErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobsControllerFindAllResponses = {
    default: Array<JobsDto>;
};

export type JobsControllerFindAllResponse = JobsControllerFindAllResponses[keyof JobsControllerFindAllResponses];

export type JobsControllerCreateData = {
    body: CreateJobDto;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type JobsControllerCreateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobsControllerCreateResponses = {
    default: string;
};

export type JobsControllerCreateResponse = JobsControllerCreateResponses[keyof JobsControllerCreateResponses];

export type JobsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type JobsControllerRemoveErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobsControllerRemoveResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobsControllerRemoveResponse = JobsControllerRemoveResponses[keyof JobsControllerRemoveResponses];

export type JobsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type JobsControllerFindOneErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobsControllerFindOneResponses = {
    default: JobsDto;
};

export type JobsControllerFindOneResponse = JobsControllerFindOneResponses[keyof JobsControllerFindOneResponses];

export type JobsControllerUpdateData = {
    body: UpdateJobDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type JobsControllerUpdateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobsControllerUpdateResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobsControllerUpdateResponse = JobsControllerUpdateResponses[keyof JobsControllerUpdateResponses];

export type JobCandidateControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/job-candidate';
};

export type JobCandidateControllerFindAllErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerFindAllResponses = {
    default: Array<{
        [key: string]: unknown;
    }>;
};

export type JobCandidateControllerFindAllResponse = JobCandidateControllerFindAllResponses[keyof JobCandidateControllerFindAllResponses];

export type JobCandidateControllerApplyJobsData = {
    body: CreateJobCandidateDto;
    path?: never;
    query?: never;
    url: '/job-candidate';
};

export type JobCandidateControllerApplyJobsErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerApplyJobsResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobCandidateControllerApplyJobsResponse = JobCandidateControllerApplyJobsResponses[keyof JobCandidateControllerApplyJobsResponses];

export type JobCandidateControllerGetMyApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/job-candidate/me';
};

export type JobCandidateControllerGetMyApplicationsErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerGetMyApplicationsResponses = {
    default: Array<string>;
};

export type JobCandidateControllerGetMyApplicationsResponse = JobCandidateControllerGetMyApplicationsResponses[keyof JobCandidateControllerGetMyApplicationsResponses];

export type JobCandidateControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/job-candidate/{id}';
};

export type JobCandidateControllerRemoveErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerRemoveResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobCandidateControllerRemoveResponse = JobCandidateControllerRemoveResponses[keyof JobCandidateControllerRemoveResponses];

export type JobCandidateControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/job-candidate/{id}';
};

export type JobCandidateControllerFindOneErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerFindOneResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobCandidateControllerFindOneResponse = JobCandidateControllerFindOneResponses[keyof JobCandidateControllerFindOneResponses];

export type JobCandidateControllerUpdateStatusData = {
    body: UpdateJobCandidateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/job-candidate/{id}';
};

export type JobCandidateControllerUpdateStatusErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerUpdateStatusResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type JobCandidateControllerUpdateStatusResponse = JobCandidateControllerUpdateStatusResponses[keyof JobCandidateControllerUpdateStatusResponses];

export type JobCandidateControllerGetCandidatesByJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/job-candidate/job/{jobId}';
};

export type JobCandidateControllerGetCandidatesByJobErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type JobCandidateControllerGetCandidatesByJobResponses = {
    default: Array<{
        [key: string]: unknown;
    }>;
};

export type JobCandidateControllerGetCandidatesByJobResponse = JobCandidateControllerGetCandidatesByJobResponses[keyof JobCandidateControllerGetCandidatesByJobResponses];

export type NotificationsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type NotificationsControllerFindAllErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: Array<NotificationDto>;
};

export type NotificationsControllerFindAllError = NotificationsControllerFindAllErrors[keyof NotificationsControllerFindAllErrors];

export type NotificationsControllerFindAllResponses = {
    200: Array<NotificationDto>;
};

export type NotificationsControllerFindAllResponse = NotificationsControllerFindAllResponses[keyof NotificationsControllerFindAllResponses];

export type NotificationsControllerCreateData = {
    body: CreateNotificationDto;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type NotificationsControllerCreateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: NotificationDto;
};

export type NotificationsControllerCreateError = NotificationsControllerCreateErrors[keyof NotificationsControllerCreateErrors];

export type NotificationsControllerCreateResponses = {
    201: NotificationDto;
};

export type NotificationsControllerCreateResponse = NotificationsControllerCreateResponses[keyof NotificationsControllerCreateResponses];

export type NotificationsControllerFindUnreadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread';
};

export type NotificationsControllerFindUnreadErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: Array<NotificationDto>;
};

export type NotificationsControllerFindUnreadError = NotificationsControllerFindUnreadErrors[keyof NotificationsControllerFindUnreadErrors];

export type NotificationsControllerFindUnreadResponses = {
    200: Array<NotificationDto>;
};

export type NotificationsControllerFindUnreadResponse = NotificationsControllerFindUnreadResponses[keyof NotificationsControllerFindUnreadResponses];

export type NotificationsControllerGetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread/count';
};

export type NotificationsControllerGetUnreadCountErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: unknown;
};

export type NotificationsControllerGetUnreadCountResponses = {
    200: {
        count?: number;
    };
};

export type NotificationsControllerGetUnreadCountResponse = NotificationsControllerGetUnreadCountResponses[keyof NotificationsControllerGetUnreadCountResponses];

export type NotificationsControllerMarkAsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type NotificationsControllerMarkAsReadErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: NotificationDto;
};

export type NotificationsControllerMarkAsReadError = NotificationsControllerMarkAsReadErrors[keyof NotificationsControllerMarkAsReadErrors];

export type NotificationsControllerMarkAsReadResponses = {
    200: NotificationDto;
};

export type NotificationsControllerMarkAsReadResponse = NotificationsControllerMarkAsReadResponses[keyof NotificationsControllerMarkAsReadResponses];

export type NotificationsControllerMarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type NotificationsControllerMarkAllAsReadErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: unknown;
};

export type NotificationsControllerMarkAllAsReadResponses = {
    200: {
        modifiedCount?: number;
    };
};

export type NotificationsControllerMarkAllAsReadResponse = NotificationsControllerMarkAllAsReadResponses[keyof NotificationsControllerMarkAllAsReadResponses];

export type NotificationsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}';
};

export type NotificationsControllerRemoveErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: unknown;
};

export type NotificationsControllerRemoveResponses = {
    200: {
        message?: string;
    };
};

export type NotificationsControllerRemoveResponse = NotificationsControllerRemoveResponses[keyof NotificationsControllerRemoveResponses];

export type NotificationsControllerUpdateData = {
    body: UpdateNotificationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}';
};

export type NotificationsControllerUpdateErrors = {
    /**
     * Internal server error
     */
    500: unknown;
    default: NotificationDto;
};

export type NotificationsControllerUpdateError = NotificationsControllerUpdateErrors[keyof NotificationsControllerUpdateErrors];

export type NotificationsControllerUpdateResponses = {
    200: NotificationDto;
};

export type NotificationsControllerUpdateResponse = NotificationsControllerUpdateResponses[keyof NotificationsControllerUpdateResponses];
